### ISSUE TITLE
404 for the link "configurer"

### ISSUE THREAD

**Issue by ZerooCool** [patope/redmine-hangouts-chat#2]
I install Redmine with RVM :
https://wiki.visionduweb.fr/index.php?title=Installer_Redmine_sur_Debian_avec_RVM

Then : 

cd /opt/redmine
su - redmine
Saisir le mot de passe (redmine)
cd redmine-4.0-stable/
cd plugins/
wget https://github.com/patope/redmine-hangouts-chat/archive/master.zip
unzip master.zip
rm master.zip
cd ..

source /opt/redmine/.rvm/scripts/rvm
rvm list gemsets
rvm use gemset ruby-2.4.5@redmine-4.0-stable
bundle install --without development test
bundle exec rake redmine:plugins:migrate RAILS_ENV=production

Redémarrer Apache2 : 
sudo service apache2 restart

Le plugin apparaît bien dans la liste des plugins, et, propose un lien de configuration.

Le lien de configuration affiche une erreur 404 : 
( http://domaine.ext/settings/plugin/redmine_hangouts_chat )
404
La page à laquelle vous souhaitez accéder n'existe pas ou a été supprimée.

**Comment by patope** [comment]
I think this is same as https://github.com/sciyoshi/redmine-slack/issues/57 . Try rename plugin directory
```
mv redmine-hangouts-chat-master redmine_hangouts_chat 
```

**Comment by ZerooCool** [comment]
You are right ! This steep work !

Renommer le dossier du plugin pour ne pas avoir l'erreur suivante :
Depuis la liste des plugins de Redmine, le lien de configuration affiche une erreur 404.
http://redmine.fictif.fr/settings/plugin/redmine_hangouts_chat
404
La page à laquelle vous souhaitez accéder n'existe pas ou a été supprimée.
Renommer le dossier du plugin pour le nommer redmine_hangouts_chat

**RESOLU AVEC : 
mv redmine-hangouts-chat-master/ redmine_hangouts_chat/**
