### ISSUE TITLE
I see nothing from slack

### ISSUE THREAD

**Issue by ZerooCool** [patope/redmine-hangouts-chat#4]
With Debian 9 + RVM + Redmine 4.0.2 Stable

# Depuis la configuration du plugin dans Redmine :
Hangouts Chat URL
Generate an "Incoming WebHook" URL from the apps configuration page on Hangouts Chat. 
Aller sur Slack avec le lien suivant pour créer l'adresse URL du "Webhooks entrants" : https://slack.com/apps/build/custom-integration
**OK ! I have the link.**

Hangouts Chat Thread
The messages can be threaded a per-project basis by creating a project custom field named "Hangouts Chat Thread" (without quotes). 
Le nom du salon cible : **#my-chan**

Hangouts Chat Icon
Configurer l'icône qui sera utilisée devant le message posté sur Slack.
**I don't add.**

Hangouts Chat Username
**my-bot-redmine**

Display Watchers?
Afficher les observateurs? **Yes**.

Post Issue Updates?
**Checked**

Post Wiki Updates?
**NO**
( If checked a bog was display from a wiki page when update and save )

Enregistrer la configuration de Redmine.
**Save.**

From Slack : 

# Depuis Slack :
Générer un **"Webhooks entrants"** depuis le lien **https://slack.com/apps/build/custom-integration** OK 
-> **#my-chan**

Ajouter un descriptif : **Nouveau message en provenance de Redmine.**
Personnaliser le nom d’utilisateur : **my-bot-redmine**

Valider cette configuration.

Un message apparaît dans le salon **#my-chan** :
Utilisateur [22 h 00] **a ajouté une intégration à cette chaîne : incoming-webhook**
Utilisateur [22 h 10] **a ajouté une intégration à cette chaîne : my-bot-redmine**

Then, when i post a new issue, i see nothing to the channel #my-chan
The same ( with a bogue ) for a wiki page.

**Comment by ZerooCool** [comment]
My tutorial : https://wiki.visionduweb.fr/index.php?title=Installer_Redmine_sur_Debian#Cr.C3.A9er_un_compte_et_un_projet_depuis_Slack

**Comment by ZerooCool** [comment]
For the moment, i can't have any notification.

Resolving dependencies...
Using rake 12.3.2
Using concurrent-ruby 1.1.5
Using i18n 0.7.0
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.2.1
Using builder 3.2.3
Using erubi 1.8.0
Using mini_portile2 2.4.0
Using nokogiri 1.10.2
Using rails-dom-testing 2.0.3
Using crass 1.0.4
Using loofah 2.2.3
Using rails-html-sanitizer 1.0.4
Using actionview 5.2.2.1
Using rack 2.0.6
Using rack-test 1.1.0
Using actionpack 5.2.2.1
Using nio4r 2.3.1
Using websocket-extensions 0.1.3
Using websocket-driver 0.7.0
Using actioncable 5.2.2.1
Using globalid 0.4.2
Using activejob 5.2.2.1
Using mini_mime 1.0.1
Using mail 2.7.1
Using actionmailer 5.2.2.1
Using method_source 0.9.2
Using thor 0.20.3
Using railties 5.2.2.1
Using actionpack-xml_parser 2.0.1
Using activemodel 5.2.2.1
Using arel 9.0.0
Using activerecord 5.2.2.1
Using mimemagic 0.3.3
Using marcel 0.3.3
Using activestorage 5.2.2.1
Using public_suffix 3.0.3
Using addressable 2.6.0
Using bundler 1.16.6
Using css_parser 1.7.0
Using csv 3.0.5
Using htmlentities 4.3.4
Fetching httpclient 2.8.3
Installing httpclient 2.8.3
Using mysql2 0.5.2
Using net-ldap 0.16.1
Using ruby-openid 2.3.0
Using rack-openid 1.4.2
Using sprockets 3.7.2
Using sprockets-rails 3.2.1
Using rails 5.2.2.1
Using rbpdf-font 1.19.1
Using rbpdf 1.19.8
Using redcarpet 3.4.0
Using request_store 1.0.5
Using rmagick 2.16.0
Using roadie 3.4.0
Using roadie-rails 1.3.0
Using rouge 3.3.0
Bundle complete! 28 Gemfile dependencies, 60 gems now installed.
Gems in the groups development, test and develop,test,postgresql,sqlite were not installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

~/redmine-4.0-stable$ gem install httpclient
Successfully installed httpclient-2.8.3
Parsing documentation for httpclient-2.8.3
Installing ri documentation for httpclient-2.8.3
Done installing documentation for httpclient after 2 seconds
1 gem installed

**Comment by patope** [comment]
This is [Google Hangouts Chat](https://gsuite.google.com/products/chat/) plugin, based on original Slack plugin. Slack plugin is here https://github.com/sciyoshi/redmine-slack . You need webhook URL for you target channel. Option is under channel menu as "Configure webhook"
![image](https://user-images.githubusercontent.com/63479/55780132-eb010500-5aaf-11e9-93b7-fee2a735af35.png)

**Comment by patope** [comment]
Not relevant.
